### ISSUE TITLE
SNI - does 'www.' really indicate an incorrect hostname?

### ISSUE THREAD

**Issue by ElardusE** [tomato42/tlslite-ng#278]
The test 'test-invalid-server-name-extension.py', has a subtest 'incorrect SNI'. It prepends 'www.' to the hostname and expects the server to reply with an alert.

RFC 6066, however, states that the hostname "contains the fully qualified DNS hostname of the server". And an FQDH typically includes a dot.

I suspect the test, therefore, is not correct to expect the server to reply with an alert.

Example run:

    incorrect SNI ...
    Error encountered while processing node <tlsfuzzer.expect.ExpectAlert object at 0x139dad0> (child: <tlsfuzzer.expect.ExpectServerHello object at 0x139db10>) with last message being: <tlslite.messages.Message object at 0x13a14d0>
    Error while processing
    Traceback (most recent call last):
      File "test-invalid-server-name-extension.py", line 468, in main
        runner.run()
      File "/root/tlsfuzzer/tlsfuzzer/runner.py", line 210, in run
        RecordHeader2)))
    AssertionError: Unexpected message from peer: Handshake(server_hello)

    SNI extension test version 3
    Test end
    successful: 0
    failed: 1
      'incorrect SNI'

**Comment by tomato42** [comment]
(side note: I think you intended to file this bug against https://github.com/tomato42/tlsfuzzer )

it's not an incorrect FQDN, but it is incorrect _hostname_

if the server is configured to support only the `www.`-less one, it should reject the one with `www.` prepended. This case tests specifically if the other rejections happen because of FQDN sanity check or if the hostname really is unrecognised

if you take a look at the test case code, you'll see that while it expects an Alert, it does not expect a connection close:

https://github.com/tomato42/tlsfuzzer/blob/24b634cde9a403d9808c43ea16f15f08746b8222/scripts/test-invalid-server-name-extension.py#L215-L251

**Comment by ElardusE** [comment]
(Correct. I guess after registering I somehow got into the wrong project)

Ah, thanks. Was not aware that some tests depend on specific server setups - just fired up a default OpenSSL server on the other end.

**Comment by tomato42** [comment]
> Ah, thanks. Was not aware that some tests depend on specific server setups - just fired up a default OpenSSL server on the other end.

yes, they do, and unfortunately it's a bit under-documented; the most reliable source is to look at retention script for tlslite-ng: (https://github.com/tomato42/tlsfuzzer/blob/master/tests/tlslite-ng.json) and compare it with the defaults and configuration of tlslite-ng for particular test cases; but optimally, that information should be printed by the script on end of execution (before the summary)
