### ISSUE TITLE
Support for remote chain verification?

### ISSUE THREAD

**Issue by echee2** [tomato42/tlslite-ng#353]
Hi there.  Newbie question:  We're looking to use tlslite-ng for TLS 1.2 support in python 2.6 (python client). 

Functional and performance tests look good but we're trying to figure out if the library provides functionality for client to verify a server's certificate chain.

Our dev team doesn't have much expertise TLS/PKI.  The tlslite-ng README talks about supplying a Checker. But looking at source code, the provided `Checker` implementation seems to just compare end-entity certificate with whatever fingerprint it is initialized with. (Whereas support for full chain verification iiuc should include digital signature verification, chain of trust, validity periods, revocation status?)  

If tlslite-ng doesn't support remote chain checking, any advice on alternate libraries (python 2.6)?  Thank you very much.

**Comment by tomato42** [comment]
> Whereas support for full chain verification iiuc should include digital signature verification, chain of trust, validity periods, revocation status?

among other things, yes; for a modern verifier, you also need to check extensions: name constraints, policy constraints, basic key usage, extended key usage, alternative subject names...

> If tlslite-ng doesn't support remote chain checking, any advice on alternate libraries (python 2.6)? Thank you very much.

yes, the readme is correct, the certificate verification is not implemented

You should be able to use openssl, either through pycrypto or m2crypto. 

In general, I would strongly suggest migrating off of python 2.6 if you do not have a support contract that provides you with a version that works with a maintained openssl 1.0.2. The reason why we support python 2.6 in tlslite-ng is because we use it as the backend for [`tlsfuzzer`](https://github.com/tomato42/tlsfuzzer) – that is, for testing *other* implementations; not for use in production (see the [security policy](https://github.com/tomato42/tlslite-ng/blob/master/SECURITY.md)).

**Comment by echee2** [comment]
Thank you very much for your guidance.  (We need 2.6 to continue supporting customers who haven't upgraded).

One follow up question regarding your security policy, please:

We're trying to understand if the described risk are less relevant when using `tlslite-ng` exclusively in a client which our customers install.  Do the risks (such as timing attacks) mainly pertain to when running `tlslite-ng` server side?  

Thank you again.

**Comment by tomato42** [comment]
it impacts both server and client, I'd say how easy it is to exploit depends more on the environment it is running in that on what side of the connection it is working as

but that's more outside my area of expertise – I focus more on detecting exploitable behaviour than how to exploit such behaviour – so it's hard for me to say which exact scenario is more exploitable than the other, especially when we're talking such detail

**Comment by echee2** [comment]
Your perspective is much appreciated.  Thanks!
