### ISSUE TITLE
Session Ticket Extension Support

### ISSUE THREAD

**Issue by AyJayHam** [tomato42/tlslite-ng#401]
I hope that i didn't oversee anything but from my point of view there is currently no client side Ticket Extension support. 

Is there any way to implement it?

I hope the question is specific enough.

**Comment by tomato42** [comment]
session tickets are fully supported in TLS 1.3

For TLS 1.2 and earlier, that is tracked in #60 so I'm closing this as duplicate

As far as how to implement it: for client side, it's very simple, the client just needs to store a blob it received from server and then send it when resuming session: it's actually supported in tlsfuzzer for earlier protocols, it's also somewhat similar to the TLS 1.3 approach.

For server side it's more complex as the server needs to be able to serialise its internal state and send it to client, but that is essentially the same thing it needs to do for TLS 1.3, so that code can be used as a template.
